classes/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^$', 'classes.views.index', name = 'index'),
    url(r'^criar$', 'classes.views.create_class', name = 'create'),
    url(r'^editar/(?P<id>\d+)$', 'classes.views.edit_class', name= 'edit'),
    url(r'^remove/(?P<id>\d+)$', 'classes.views.remove', name = 'remove'),
    url(r'^registrar/(?P<key>.+)$', 'classes.views.register', name = 'register'),
    url(r'^badges/(?P<id>\d+)$', 'classes.views.give_badges', name = 'give_badges'),
    url(r'^pontuacao/(?P<id>\d+)$', 'classes.views.give_rewards', name = 'give_rewards'),
    url(r'^confirmar-registro/(?P<key>.+)$', 'classes.views.confirm_register', name = 'confirm_register'),
    url(r'^(?P<id>\d+)$', 'classes.views.view', name = 'view'),
    url(r'^estatisticas/(?P<id>\d+)$', 'classes.views.stats', name = 'stats'),
    url(r'^teachers/(?P<id>\d+)$', 'classes.views.atribuir_professor', name='atribuir_professor'),
]

jornada/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from accounts import urls as accounts_urls
from classes import urls as classes_urls
from rewards import urls as rewards_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'jornada.views.index', name = 'index'),
    url(r'^usuario/', include(accounts_urls, namespace="Accounts")),
    url(r'^turmas/', include(classes_urls, namespace="Classes")),
    url(r'^pontos/', include(rewards_urls, namespace="Rewards")),
    url(r'^estatisticas$', 'jornada.views.statistics', name = 'statistics'),
    # ADICIONAR A MINHA URL AQUI
]

rewards/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from accounts import urls as accounts_urls
from classes import urls as classes_urls

urlpatterns = [
    url(r'^$', 'rewards.views.index', name = 'index'),
    url(r'^criar-pontuacao/$', 'rewards.views.create_reward', name = 'create_reward'),
    url(r'^criar-badge/$', 'rewards.views.create_badge', name = 'create_badge'),
]

jornada/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from jornada.util import is_teacher
from classes.models import Class
from accounts.models import Teacher, Student

@login_required(login_url='usuario/login/')
def index(request):
	context = {'index_active': True}

	if is_teacher(request.user):
		context['classes'] = Class.objects.filter(teachers__in=[Teacher.objects.get(user=request.user)])
	else:
		context['classes'] =  Class.objects.filter(students__in=[Student.objects.get(user=request.user)])

	return render(request, 'index.html', context)

def statistics(request):
	context = {'statistics_active': True}
	classes_context = []

	if is_teacher(request.user):
		classes = Class.objects.filter(teachers__in=[Teacher.objects.get(user=request.user)])
	else:
		classes = Class.objects.filter(students__in=[Student.objects.get(user=request.user)])

	for entry in classes:
		students = []
		for student in entry.students.all().order_by('user__first_name', 'user__last_name'):
			students.append({'name': str(student), 'total': student.total_value_in_class(entry)})
		classes_context.append((entry, students))

	context['classes'] = classes_context
	
	return render(request, 'reports.html', context)

jornada/templates/students/student_rewards.html
{% load staticfiles %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Criação/Edição de Turma - Jornada</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta name="apple-mobile-web-app-capable" content="yes">
<link href="{% static "css/bootstrap_new.css" %}" rel="stylesheet">

<link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600"
        rel="stylesheet">
<link href="{% static "css/font-awesome.css" %}" rel="stylesheet">
<link href="{% static "css/style.css" %}" rel="stylesheet">
<link href="{% static "css/pages/dashboard.css" %}" rel="stylesheet">
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>

{% include 'nav.html' %}


<!-- /subnavbar -->
<div class="main">
  <div class="main-inner">

    <div class="container">

      <div class="row">
        <div class="col-md-6">
          <div class="panel">
            <div class="panel-header">
              <h2 class="pull-left">Pontuações</h2>
              <br style="clear: both" /> 
            </div>

          {% for reward in rewards %}
            <div class="panel-item">
              <a href="#">
                <strong>{{ reward.name }}</strong> <br />
                {{ reward.description }}
              </a>
            </div>
          {% endfor %}
          </div>
        </div>

        <div class="col-md-6">
          <div class="panel">
            <div class="panel-header">
              <h2 class="pull-left">Badges</h2>
              <br style="clear: both" /> 
            </div>

          {% for badge in badges %}
            <div class="panel-item">
              <a href="#">
                <strong>{{ badge.name }}</strong> <br />
                {{ badge.description }}
              </a>
            </div>
          {% endfor %}

          </div>
        </div>

      </div>

    </div>

    <!-- /container --> 
  </div>
  <!-- /main-inner --> 
</div>
<!-- /main -->

<!-- Modal -->
<!-- <div class="modal fade" id="create-reward" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <form method="POST" action="{% url 'Rewards:create_reward' %}">
  {% csrf_token %}
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Modal title</h4>
        </div>
        <div class="modal-body">
          <div style="padding: 10px 30px 20px 20px">     
            <div class="form-group">
              <label for="name">Nome</label>
              {% render_field reward_form.name placeholder="Ex: Chegar no hoário certo" class="form-control" %}
            </div>
            <div class="form-group">
              <label for="name">Descrição</label>
              {% render_field reward_form.description class="form-control" %}
            </div>
            <div class="form-group">
              <label for="name">Valor</label>
              {% render_field reward_form.value class="form-control" type="number" %}
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </div>
    </div>
  </form>
</div> -->

<!-- Modal -->
<!-- <div class="modal fade" id="create-badge" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <form method="POST" action="{% url 'Rewards:create_badge' %}">
  {% csrf_token %}
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Modal title</h4>
        </div>
        <div class="modal-body">
          <div style="padding: 10px 30px 20px 20px">     
            <div class="form-group">
              <label for="name">Nome</label>
              {% render_field badge_form.name placeholder="Ex: Aluno pontual" class="form-control" %}
            </div>
            <div class="form-group">
              <label for="name">Descrição</label>
              {% render_field badge_form.description class="form-control" %}
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </div>
    </div>
  </form>
</div> -->

{% include "footer.html" %}

<!-- Le javascript
================================================== --> 
<!-- Placed at the end of the document so the pages load faster --> 
<script src="{% static "js/jquery-1.7.2.min.js" %}"></script> 
<script src="{% static "js/bootstrap.js" %}"></script>

 
<script src="{% static "js/base.js" %}"></script> 

</body>
</html>

jornada/templates/students/view_student.html
<div class="widget widget-table action-table">
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Jornada</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta name="apple-mobile-web-app-capable" content="yes">
<link href="{% static "css/bootstrap_new.css" %}" rel="stylesheet">
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600"
        rel="stylesheet">
<link href="{% static "css/font-awesome.css" %}" rel="stylesheet">
<link href="{% static "css/style.css" %}" rel="stylesheet">
<link href="{% static "css/pages/dashboard.css" %}" rel="stylesheet">

  <style type="text/css">
    .test{
      margin-bottom: 2%;
      margin-right: 9%;
    }
    .column{
    }
    .classborder{
      border-style:solid;
      border-color: #00ba8b;
    }
    .classcontent{
      text-indent: 10%;
      font-family: monospace;
    }
    .classtitle{
      text-align: center;
      font-family: monospace;
    }
    .studentcontent{
      text-indent: 5%;  
      font-family: monospace;
    }
    .shot{
      padding-left: 4%;
      padding-right: 10%;
    }

    .background-white{
      background: #fff;
    }

    #created-by{
      font-size: 12px;
      margin-top: 0px;
    }

    #class-data-list{
      margin-top: 10px;
      padding: 10px 0px 0px 0px;
      list-style-type: none;
    }

    #class-data-list li{
      font-size: 14px;
      border-top: solid 1px #F2F2F2;
      padding: 10px;
    }

    #badgecontent{
      margin: 0px;
      padding: 0px;
    }

    #badgecontent li{
      display: block;
      border-bottom: solid 1px #ccc;
      padding: 10px 20px;
      color: #a5a5a5;
    }

    #badgecontent li strong{
      font-size: 14px;
      color: #0e0e0e;
    }

    #teachers{
      margin:0px !important ;
      list-style-type: none;
      font-size: 14px;
      padding: 0px;
    }

    #teachers li{
      margin: 0px;
      border-top: none;
      border-bottom: solid 1px #F2F2F2;
      padding: 10px;
    }

    .title{
      background: #F2F2F2;
      padding: 10px;
      margin: 0px;
      margin-top: 20px;
      text-align: center;
    }
  </style>
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>

{% include 'nav.html' %}

<!-- /subnavbar -->
<div class="main">
  <div class="main-inner">
    <div class="container">

      <div class="row column">
        <div id="class-data" class="col-md-4 background-white">
          <h1>{{ student }}</h1>

          <ul id="class-data-list">
            <li><strong>Escola:</strong> {{ student.school }}</li>
            <li><strong>Série:</strong> {{ class.grade }}</li>
          </ul>
            
          <h3 class="title">Turmas</h3>

          <ul id="teachers">
              {% for class in  classes %}
              <li><a href="{% url 'Classes:view' id=class.pk %}">{{ class.name }}</a></li>
              {% endfor %}
          </ul>
        </div>

        <div class="col-md-8 shot">
          <div class="widget widget-table action-table">
            <div class="widget-content">
              <h3 class="classtitle" align="center">Badges</h3>
              <ul id="badgecontent">
                {% for badge in badges %}
                 <li>
                  <strong>{{ badge.badge.name }}</strong>
                  {{ badge.badge.description }}
                 </li>
                {% empty %}
                  <h5 class="studentcontent">Esse alunos não possui badges</h5>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>

      <!-- /row --> 
    </div>
    <!-- /container --> 
  </div>
  <!-- /main-inner --> 
</div>
<!-- /main -->

<!-- Modal -->
<!-- <div class="modal fade" id="students-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Convidar alunos</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" id="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" id="button" class="btn btn-primary">Salvar</button>
      </div>
    </div>
  </div>
</div> -->

{% include 'footer.html' %}

<!-- /footer --> 
<!-- Le javascript
================================================== --> 
<!-- Placed at the end of the document so the pages load faster --> 
<script src="{% static "js/jquery-1.7.2.min.js" %}"></script> 

<script src="{% static "js/bootstrap.js" %}"></script>
 
<script src="{% static "js/base.js" %}"></script> 


</body>
</html>