accounts/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^cadastro-professor$', 'accounts.views.signup_teacher', name = 'signup_teacher'),
    url(r'^cadastro-aluno$', 'accounts.views.signup_student', name = 'signup_student'),
    url(r'^login/', 'accounts.views.login', name = "login"),
    url(r'^editar/', 'accounts.views.edit', name = "edit"),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name= 'logout'),
    url(r'^perfil-aluno/(?P<id>\d+)/$', 'accounts.views.view_student', name='view'),
    url(r'^perfil-professor/(?P<id>\d+)/$', 'accounts.views.view_teacher', name='viewteacher')
]

classes/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^$', 'classes.views.index', name = 'index'),
    url(r'^criar$', 'classes.views.create_class', name = 'create'),
    url(r'^editar/(?P<id>\d+)$', 'classes.views.edit_class', name= 'edit'),
    url(r'^remove/(?P<id>\d+)$', 'classes.views.remove', name = 'remove'),
    url(r'^registrar/(?P<key>.+)$', 'classes.views.register', name = 'register'),
    url(r'^badges/(?P<id>\d+)$', 'classes.views.give_badges', name = 'give_badges'),
    url(r'^pontuacao/(?P<id>\d+)$', 'classes.views.give_rewards', name = 'give_rewards'),
    url(r'^confirmar-registro/(?P<key>.+)$', 'classes.views.confirm_register', name = 'confirm_register'),
    url(r'^(?P<id>\d+)$', 'classes.views.view', name = 'view'),
    url(r'^estatisticas/(?P<id>\d+)$', 'classes.views.stats', name = 'stats'),
    url(r'^teachers/(?P<id>\d+)$', 'classes.views.atribuir_professor', name='atribuir_professor'),
]

jornada/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from accounts import urls as accounts_urls
from classes import urls as classes_urls
from rewards import urls as rewards_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'jornada.views.index', name = 'index'),
    url(r'^usuario/', include(accounts_urls, namespace="Accounts")),
    url(r'^turmas/', include(classes_urls, namespace="Classes")),
    url(r'^pontos/', include(rewards_urls, namespace="Rewards")),
    url(r'^estatisticas$', 'jornada.views.statistics', name = 'statistics'),
    # ADICIONAR A MINHA URL AQUI
]

classes/models.py
from django.db import models

from accounts.models import Teacher, Student, GRADE_CHOICES

# Create your models here.

GRADE_CHOICES = (
	('1ef', '1º ano'),
	('2ef', '2º ano'),
	('3ef', '3º ano'),
	('4ef', '4º ano'),
	('5ef', '5º ano'),
	('6ef', '6º ano'),
	('7ef', '7º ano'),
	('8ef', '8º ano'),
	('9ef', '9º ano'),
	('1em', '1º ano EM'),
	('2em', '2º ano EM'),
	('3em', '3º ano EM'),
)

class Class(models.Model):
	teachers = models.ManyToManyField(Teacher)
	name = models.CharField(max_length=50, blank=True)
	grade = models.CharField(max_length=50, blank=True, choices=GRADE_CHOICES)
	discipline = models.CharField(max_length=50, blank=True)
	time = models.CharField(max_length=100, blank=True)
	location = models.CharField(max_length=100, blank=True)
	students = models.ManyToManyField(Student)
	description = models.CharField(max_length=200, blank=True)

	def __str__(self):
	   return self.name + " - " + self.teachers.all()[0].user.first_name

classes/forms.py
from django.forms import ModelForm
from classes.models import Class


class ClassForm(ModelForm):

    class Meta:
        model = Class
        fields = ['name', 'grade', 'discipline', 'time', 'location', 'description']

classes/views.py
from django.shortcuts import render, redirect
from classes.forms import ClassForm
from classes.models import Class
from django.contrib.auth.decorators import login_required
from jornada.util import is_teacher
from django.core.urlresolvers import reverse
from rewards.models import Badge, Reward, BadgeStudentClass, RewardStudentClass
from django.contrib import messages

from datetime import datetime, date

import base64

from accounts.models import Teacher,Student

@login_required(login_url='/usuario/login/')
def index(request):

	teacher = is_teacher(request.user)

	if teacher:
		classes = Class.objects.filter(teachers__in=[Teacher.objects.get(user=request.user)])
	else:
		classes = Class.objects.filter(students__in=[Student.objects.get(user=request.user)])

	return render(request, 'classes/index.html', {
		'classes': classes,
		'classes_active': True,
		'is_teacher': teacher
	})

@login_required(login_url='/usuario/login/')
def remove(request, id):

	if not is_teacher(request.user):
		return redirect('index')

	if not Class.objects.filter(pk=id, teachers__in=[Teacher.objects.get(user=request.user)]):
		return redirect('index')

	Class.objects.get(pk=id).delete()

	return redirect('Classes:index')


@login_required(login_url='/usuario/login/')
def create_class(request):

	if not is_teacher(request.user):
		return redirect('index')

	class_form = ClassForm(request.POST or None)

	if class_form.is_valid():
		classe = class_form.save()
		classe.teachers.add(Teacher.objects.get(user=request.user))
		classe.save()
		return redirect('Classes:index')

	return render(request, 'classes/form.html', {
		'form': class_form,
		'edit': False
	})

@login_required(login_url='/usuario/login/')
def edit_class(request, id):

	if not is_teacher(request.user):
		return redirect('index')

	if not Class.objects.filter(pk=id, teachers__in=[Teacher.objects.get(user=request.user)]):
		return redirect('Classes:index')


	my_class = Class.objects.get(pk=id)
	class_form = ClassForm(request.POST or None, instance = my_class)

	if class_form.is_valid():
		my_class.save()
		return redirect('Classes:index')
		

	return render(request, 'classes/form.html', {
		'form': class_form,
		'edit': True
	})

@login_required(login_url='/usuario/login/')
def view(request, id):

	obj = Class.objects.get(pk=id)

	aux = set(Teacher.objects.all())
	aux2 = set(obj.teachers.all())

	aux -= aux2
	
	students = obj.students.all()

	for student in students:
		rewards = RewardStudentClass.objects.filter(student=student, classe=obj)
		student.score = 0
		for reward in rewards:
			student.score += reward.reward.value

	students = list(students)

	students.sort(key=lambda x: x.score, reverse=True)

	rewards = RewardStudentClass.objects.filter(classe=obj)
	ranking_rewards = {}
	for s in students:
		for r in rewards:
			count = RewardStudentClass.objects.filter(classe=obj, student=s).count()
			if not r.reward.pk in ranking_rewards or ranking_rewards[r.reward.pk]['count'] < count:
				ranking_rewards[r.reward.pk] = {
					'count': count,
					'reward': r.reward,
					'student': s
				} 

	ranking_rewards = [ranking_rewards[r] for r in ranking_rewards]

	context={
		'class': obj,
		'key': base64.b64encode(bytes(id, 'utf-8')),
		'is_teacher': is_teacher(request.user),
		'teachers': aux,
		'students': students,
		'ranking_rewards': ranking_rewards

	}
	return render(request, 'classes/view_class.html', context)

@login_required(login_url='/usuario/login/')
def register(request, key):

	if is_teacher(request.user):
		return redirect('Classes:index')

	student_obj = Student.objects.get(user=request.user)

	pk = base64.b64decode(key)
	obj = Class.objects.get(pk=pk)

	if Class.objects.filter(pk=pk, students__in=[student_obj]):
		return redirect(reverse('Classes:view', kwargs={'id':pk}))

	# obj.students.add(student_obj)
	# obj.save()

	return render(request, 'classes/register.html', {
		'class': Class.objects.get(pk=pk),
		'key': key
	})

def confirm_register(request, key):
	if is_teacher(request.user):
		return redirect('Classes:index')

	student_obj = Student.objects.get(user=request.user)

	pk = base64.b64decode(key)
	obj = Class.objects.get(pk=pk)

	if Class.objects.filter(pk=pk, students__in=[student_obj]):
		return redirect(reverse('Classes:view', kwargs={'id':pk}))

	obj.students.add(student_obj)
	obj.save()

	return redirect('Classes:index')

def give_badges(request, id):

	obj = Class.objects.get(pk=id)
	badges = []
	for teacher in obj.teachers.all():
		badges = badges + list(Badge.objects.filter(created_by=teacher.user))

	if request.method == 'POST':
		badge = Badge.objects.get(pk=request.POST.get('badge'))
		students = Student.objects.filter(pk__in=request.POST.getlist('students[]'))
		for student in students:
			bsc = BadgeStudentClass()
			bsc.student = student
			bsc.badge = badge
			bsc.classe = obj
			bsc.save()
		messages.success(request, 'Badges atribuídas com sucesso.')

	return render(request, 'classes/give_badges.html', {
		'class': obj,
		'badges': badges
	})

def atribuir_professor(request, id):

	if request.method == 'POST':
		prof = Teacher.objects.filter(pk__in=request.POST.getlist('teachers[]'))
		classe = Class.objects.get(pk=id)

		for teacher in prof:
			classe.teachers.add(teacher)
			classe.save()
		messages.success(request, 'Professor atribuído com sucesso.')

	return redirect(reverse('Classes:view', kwargs={'id':id}))

def give_rewards(request, id):

	obj = Class.objects.get(pk=id)
	rewards = []
	for teacher in obj.teachers.all():
		rewards = rewards + list(Reward.objects.filter(created_by=teacher.user))

	if request.method == 'POST':
		reward = Reward.objects.get(pk=request.POST.get('reward'))
		students = Student.objects.filter(pk__in=request.POST.getlist('students[]'))
		for student in students:
			bsc = RewardStudentClass()
			bsc.student = student
			bsc.reward = reward
			bsc.classe = obj
			bsc.save()
		messages.success(request, 'Pontuações atribuídas com sucesso.')

	return render(request, 'classes/give_rewards.html', {
		'class': obj,
		'rewards': rewards
	})

@login_required(login_url='/usuario/login/')
def stats(request, id):

	obj = Class.objects.get(pk=id)

	students = obj.students.all()

	selected = False

	if request.GET.get('start') and request.GET.get('end'):
		selected = True

		initial_date = datetime.strptime('01/01/2000', '%d/%m/%Y')
		start_date = datetime.strptime(request.GET.get('start') + ' 00:00', '%d/%m/%Y %H:%M')
		end_date = datetime.strptime(request.GET.get('end') + ' 23:59', '%d/%m/%Y %H:%M')

		for student in students:
			initial_rewards = RewardStudentClass.objects.filter(student=student, classe=obj, created__range=(initial_date, start_date))
			student.initial_score = 0
			for r in initial_rewards:
				student.initial_score += r.reward.value

			rewards = RewardStudentClass.objects.filter(student=student, classe=obj, created__range=(start_date, end_date))
			student.score = 0
			for r in rewards:
				student.score += r.reward.value
			
			if student.score < student.initial_score:
				student.score_raise = -((student.initial_score or 1)/(student.score or 1))*100
			else:
				student.score_raise = (student.score/(student.initial_score or 1))*100

			student.badges = BadgeStudentClass.objects.filter(student=student, classe=obj, created__range=(start_date, end_date))

	context={
		'class': obj,
		'is_teacher': is_teacher(request.user),
		'students': students,
		'selected': selected
	}
	return render(request, 'classes/stats.html', context)

jornada/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from jornada.util import is_teacher
from classes.models import Class
from accounts.models import Teacher, Student

@login_required(login_url='usuario/login/')
def index(request):
	context = {'index_active': True}

	if is_teacher(request.user):
		context['classes'] = Class.objects.filter(teachers__in=[Teacher.objects.get(user=request.user)])
	else:
		context['classes'] =  Class.objects.filter(students__in=[Student.objects.get(user=request.user)])

	return render(request, 'index.html', context)

def statistics(request):
	context = {'statistics_active': True}
	classes_context = []

	if is_teacher(request.user):
		classes = Class.objects.filter(teachers__in=[Teacher.objects.get(user=request.user)])
	else:
		classes = Class.objects.filter(students__in=[Student.objects.get(user=request.user)])

	for entry in classes:
		students = []
		for student in entry.students.all().order_by('user__first_name', 'user__last_name'):
			students.append({'name': str(student), 'total': student.total_value_in_class(entry)})
		classes_context.append((entry, students))

	context['classes'] = classes_context
	
	return render(request, 'reports.html', context)

jornada/templates/classes/index.html
<div class="widget widget-table action-table">
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Jornada</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta name="apple-mobile-web-app-capable" content="yes">
<link href="{% static "css/bootstrap_new.css" %}" rel="stylesheet">
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600"
        rel="stylesheet">
<link href="{% static "css/font-awesome.css" %}" rel="stylesheet">
<link href="{% static "css/style.css" %}" rel="stylesheet">
<link href="{% static "css/pages/dashboard.css" %}" rel="stylesheet">
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>

{% include 'nav.html' %}

<!-- /subnavbar -->
<div class="main">
  <div class="main-inner">
    <div class="container">
      <div class="row">

        <div class="col-md-12">

        {% if is_teacher %}
        <a class="btn btn-primary" style="margin-bottom: 20px" href="{% url 'Classes:create' %}">Criar turma</a>
        {% endif %}

           <div class="widget widget-table action-table">
            <div class="widget-header"> <i class="icon-th-list"></i>
              <h3>Turmas</h3>
            </div>
            <!-- /widget-header -->
            <div class="widget-content">
              <table class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th>Nome</th>
                    <th>Disciplina</th>
                    <th>Série</th>
                    <th>Alunos</th>
                    <th class="td-actions"> </th>
                  </tr>
                </thead>
                <tbody>
                  {% for class in classes %}
                  <tr>

                    <td><a href="{% url 'Classes:view' id=class.pk %}"> {{ class.name }} </a></td>
                    <td><a href="{% url 'Classes:view' id=class.pk %}"> {{ class.discipline }} </a></td>
                    <td><a href="{% url 'Classes:view' id=class.pk %}"> {{ class.grade }} </a></td>
                    <td><a href="{% url 'Classes:view' id=class.pk %}"> {{ class.students.count }} </a></td>

                    <td>
                        {% if is_teacher %}
                        <a data-href="{% url 'Classes:remove' id=class.pk %}" class="btn btn-danger btn-small remove-confirm"><i class="btn-icon-only icon-remove"> </i></a>
                        <a href="{% url 'Classes:edit' id=class.pk %}" class="btn btn-info btn-small"><i class="btn-icon-only icon-edit"> </i></a></td>
                        {% endif %}
                  </tr>

                  {% empty %}

                  <tr>
                    <td colspan="5"> Você não possui nenhuma turma.</td>
                  </tr>


                  {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /widget-content --> 
          </div>
        </div>

      </div>
      <!-- /row --> 
    </div>
    <!-- /container --> 
  </div>
  <!-- /main-inner --> 
</div>
<!-- /main -->

{% include 'footer.html' %}

<!-- /footer --> 
<!-- Le javascript
================================================== --> 
<!-- Placed at the end of the document so the pages load faster --> 
<script src="{% static "js/jquery-1.7.2.min.js" %}"></script> 

<script src="{% static "js/bootstrap.js" %}"></script>
 
<script src="{% static "js/base.js" %}"></script> 

<script type="text/javascript">
  
  $(document).ready(function(){
    $('.remove-confirm').click(function(){
      var r = confirm("Deseja remover a turma? Essa ação é permanente.");
      if(r) window.location = $(this).data('href')
    })
  })

</script>

</body>
</html>

jornada/templates/classes/view_class.html
<div class="widget widget-table action-table">
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Jornada</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta name="apple-mobile-web-app-capable" content="yes">
<link href="{% static "css/bootstrap_new.css" %}" rel="stylesheet">
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600"
        rel="stylesheet">
<link href="{% static "css/font-awesome.css" %}" rel="stylesheet">
<link href="{% static "css/style.css" %}" rel="stylesheet">
<link href="{% static "css/pages/dashboard.css" %}" rel="stylesheet">

  <style type="text/css">
    .test{
      margin-bottom: 2%;
      margin-right: 9%;
    }
    .column{
    }
    .classborder{
      border-style:solid;
      border-color: #00ba8b;
    }
    .classcontent{
      text-indent: 10%;
      font-family: monospace;
    }
    .classtitle{
      text-align: center;
      font-family: monospace;
    }
    .studentcontent{
      text-indent: 5%;  
      font-family: monospace;
    }
    .shot{
      padding-left: 4%;
      padding-right: 10%;
    }

    .background-white{
      background: #fff;
    }

    #created-by{
      font-size: 12px;
      margin-top: 0px;
    }

    #class-data-list{
      margin-top: 10px;
      padding: 10px 0px 0px 0px;
      list-style-type: none;
    }

    #class-data-list li{
      font-size: 14px;
      border-top: solid 1px #F2F2F2;
      padding: 10px;
    }

    #teachers{
      margin:0px !important ;
      list-style-type: none;
      font-size: 14px;
      padding: 0px;
    }

    #teachers li{
      margin: 0px;
      border-top: none;
      border-bottom: solid 1px #F2F2F2;
      padding: 10px;
    }

    .title{
      background: #F2F2F2;
      padding: 10px;
      margin: 0px;
      margin-top: 20px;
    }
    #ranking{
      padding: 20px;
      list-style-type: none;
    }
    #ranking li{
      margin: 0px 0px;
    }
    #ranking li a{
      display: block;
      background: #f2f2f2;
      padding: 20px 20px 30px 20px;  
    }

    #ranking li a h2{
      float: left;
      margin: 0px 10px;
    }

    #ranking li a strong{
      position: relative;
      top:5px;
    }
    #badgecontent{
      margin: 0px;
      padding: 0px;
    }

    #badgecontent li{
      display: block;
      border-bottom: solid 1px #ccc;
      padding: 10px 20px;
      color: #a5a5a5;
    }

    #badgecontent li strong{
      font-size: 14px;
      color: #0e0e0e;
    }

  </style>
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>

{% include 'nav.html' %}

<!-- /subnavbar -->
<div class="main">
  <div class="main-inner">
    <div class="container">

    {% if messages %}
      <div class="row">
        <div class="col-md-12">
          <div class="alert alert-success" style="padding: 20px">
            <ul>
              {% for message in messages %}
              <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
          {% endif %}

      <div class="row test" align="right">
      <a class="btn btn-primary" id="button" href="{% url 'Classes:stats' id=class.pk %}">Estatísticas da turma</a>
      {% if is_teacher %}
        <a class="btn btn-primary" id="button" href="{% url 'Classes:edit' id=class.pk %}">Editar</a> <!--  href="" -->
        <a class="btn btn-primary" id="button" href="{% url 'Classes:give_rewards' id=class.pk %}">Atribuir Pontuação</a>
        <a class="btn btn-primary" id="button" href="{% url 'Classes:give_badges' id=class.pk %}">Atribuir Badge</a>
        {% endif %}
      </div>

      <div class="row column">
        <div id="class-data" class="col-md-4 background-white">
          <h1>{{ class.name }}</h1>
          <h2 id="created-by">Criada por: Prof. {{ class.teachers.all.0 }}</h2>

          <ul id="class-data-list">
            <li><strong>Disciplina:</strong> {{ class.discipline }}</li>
            <li><strong>Série:</strong> {{ class.grade }}</li>
            <li><strong>Número de alunos: </strong>  {{ class.students.count }}</li>
            <li><strong>Link de registro: </strong> <a href="{% url 'Classes:register' key=key %}">Link</a></li>

          </ul>
            
          <h3 class="title">Professores {% if is_teacher %}<a  href="#prof-modal" data-toggle="modal" class="btn btn-primary btn-xs" style="float: right; margin-top: 2px">Adicionar</a> {% endif %}</h3>

          <ul id="teachers">
              {% for teacher in  class.teachers.all %}
              <li><a href="{% url 'Accounts:viewteacher' id=teacher.id %}">{{ teacher }}</a></li>
              {% endfor %}
          </ul>
        </div>

        <div class="col-md-8 shot">
          <div class="widget widget-table action-table">
            <div class="widget-content">
              <h3 class="classtitle" align="center">Melhores alunos</h3>
              <ul id="ranking">
                {% for student in students %}
                <li>
                  <a href="{% url 'Accounts:view' id=student.pk %}">
                    <h2 class="ranking-pos">{{ forloop.counter }}</h2>
                    <strong>{{ student }} ({{student.score}} pontos)</strong></a>
                    <br style="clear: both" />
                </li>
                {% empty %}
                <h5 class="studentcontent">Essa turma não possui alunos</h5>
                {% endfor %}
              </ul>
            </div>
          </div>

          <div class="widget widget-table action-table">
            <div class="widget-content">
              <h3 class="classtitle" align="center">Melhores alunos por pontuação</h3>
              <ul id="badgecontent">
                {% for reward in ranking_rewards %}
                 <li>
                  <strong>{{ reward.reward.name }} - {{ reward.student }}</strong>
                   Pontuação dada {{ reward.count }} vez(es)
                 </li>
                {% empty %}
                  <h5 class="studentcontent">Nenhuma pontuação foi dada para os alunos dessa turma.</h5>
                {% endfor %}
              </ul>
            </div>
          </div>

          
        </div>
      </div>

      <!-- /row --> 
    </div>
    <!-- /container --> 
  </div>
  <!-- /main-inner --> 
</div>
<!-- /main -->

<!-- Modal -->
<div class="modal fade" id="students-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Convidar alunos</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" id="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" id="button" class="btn btn-primary">Salvar</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="reward-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Atribuir pontuação</h4>
      </div>
      <div class="modal-body">
        <div style="padding: 10px 30px 20px 20px">     
          <div class="form-group">
            <label for="name">Aluno</label>
            
          </div>
          <div class="form-group">
            <label for="name">Pontuação</label>
            
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" id="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" id="button" class="btn btn-primary">Concluir</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="prof-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Atribuir Professor</h4>
      </div>
      <form action="{% url 'Classes:atribuir_professor' id=class.pk %}" method="post">
      {% csrf_token %}
      <div class="modal-body">
        <div style="padding: 10px 30px 20px 20px">     
          <div class="form-group">
          
            <label for="name">Professores</label>
              {% for teacher in teachers %} 
              <div class="toggle-btn-div">
                <label onclick="" class="toggle-btn noscript">
              <input type="checkbox" name="teachers[]" value="{{ teacher.pk }}"/> {{ teacher }}</label>
              </div>
              {% endfor %}
              
          </div> <!-- aqui -->
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" id="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="submit" id="button" class="btn btn-primary">Concluir</button>
      </div>
      </form>
    </div>
  </div>
</div>

{% include 'footer.html' %}

<!-- /footer --> 
<!-- Le javascript
================================================== --> 
<!-- Placed at the end of the document so the pages load faster --> 
<script src="{% static "js/jquery-1.7.2.min.js" %}"></script> 

<script src="{% static "js/bootstrap.js" %}"></script>
 
<script src="{% static "js/base.js" %}"></script> 

<script type="text/javascript">
  
  $(document).ready(function(){
    $('.remove-confirm').click(function(){
      var r = confirm("Deseja remover a turma? Essa ação é permanente.");
      if(r) window.location = $(this).data('href')
    })
  })

</script>

</body>
</html>