accounts/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^cadastro-professor$', 'accounts.views.signup_teacher', name = 'signup_teacher'),
    url(r'^cadastro-aluno$', 'accounts.views.signup_student', name = 'signup_student'),
    url(r'^login/', 'accounts.views.login', name = "login"),
    url(r'^editar/', 'accounts.views.edit', name = "edit"),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name= 'logout'),
    url(r'^perfil-aluno/(?P<id>\d+)/$', 'accounts.views.view_student', name='view'),
    url(r'^perfil-professor/(?P<id>\d+)/$', 'accounts.views.view_teacher', name='viewteacher')
]

classes/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^$', 'classes.views.index', name = 'index'),
    url(r'^criar$', 'classes.views.create_class', name = 'create'),
    url(r'^editar/(?P<id>\d+)$', 'classes.views.edit_class', name= 'edit'),
    url(r'^remove/(?P<id>\d+)$', 'classes.views.remove', name = 'remove'),
    url(r'^registrar/(?P<key>.+)$', 'classes.views.register', name = 'register'),
    url(r'^badges/(?P<id>\d+)$', 'classes.views.give_badges', name = 'give_badges'),
    url(r'^pontuacao/(?P<id>\d+)$', 'classes.views.give_rewards', name = 'give_rewards'),
    url(r'^confirmar-registro/(?P<key>.+)$', 'classes.views.confirm_register', name = 'confirm_register'),
    url(r'^(?P<id>\d+)$', 'classes.views.view', name = 'view'),
    url(r'^estatisticas/(?P<id>\d+)$', 'classes.views.stats', name = 'stats'),
    url(r'^teachers/(?P<id>\d+)$', 'classes.views.atribuir_professor', name='atribuir_professor'),
]

jornada/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from accounts import urls as accounts_urls
from classes import urls as classes_urls
from rewards import urls as rewards_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'jornada.views.index', name = 'index'),
    url(r'^usuario/', include(accounts_urls, namespace="Accounts")),
    url(r'^turmas/', include(classes_urls, namespace="Classes")),
    url(r'^pontos/', include(rewards_urls, namespace="Rewards")),
    url(r'^estatisticas$', 'jornada.views.statistics', name = 'statistics'),
    # ADICIONAR A MINHA URL AQUI
]

rewards/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from accounts import urls as accounts_urls
from classes import urls as classes_urls

urlpatterns = [
    url(r'^$', 'rewards.views.index', name = 'index'),
    url(r'^criar-pontuacao/$', 'rewards.views.create_reward', name = 'create_reward'),
    url(r'^criar-badge/$', 'rewards.views.create_badge', name = 'create_badge'),
]

rewards/models.py
from django.db import models

from django.contrib.auth.models import User
from accounts.models import Student
from classes.models import Class

# Create your models here.
class Reward(models.Model):
    name = models.CharField(max_length=50, blank=True)
    description = models.CharField(max_length=200, blank=True)
    value = models.IntegerField(blank=True, default = 0)
    created_by = models.ForeignKey(User)

    def __str__(self):
    	return self.name + " - Created by " + self.created_by.first_name


class Badge(models.Model):
    name = models.CharField(max_length=50, blank=True)
    description = models.CharField(max_length=200, blank=True)
    created_by = models.ForeignKey(User)

    def __str__(self):
    	return self.name + " - Created by " + self.created_by.first_name

class BadgeStudentClass(models.Model):
    badge = models.ForeignKey(Badge)
    student = models.ForeignKey(Student)
    classe = models.ForeignKey(Class)
    created = models.DateTimeField(auto_now_add=True)

class RewardStudentClass(models.Model):
    reward = models.ForeignKey(Reward)
    student = models.ForeignKey(Student)
    classe = models.ForeignKey(Class)
    created = models.DateTimeField(auto_now_add=True)

rewards/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from rewards.models import Badge, Reward

class RewardForm (ModelForm):

	class Meta:
		model = Reward
		fields = ['name', 'description', 'value']

class BadgeForm (ModelForm):

	class Meta:
		model = Badge
		fields = ['name', 'description']

jornada/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from jornada.util import is_teacher
from classes.models import Class
from accounts.models import Teacher, Student

@login_required(login_url='usuario/login/')
def index(request):
	context = {'index_active': True}

	if is_teacher(request.user):
		context['classes'] = Class.objects.filter(teachers__in=[Teacher.objects.get(user=request.user)])
	else:
		context['classes'] =  Class.objects.filter(students__in=[Student.objects.get(user=request.user)])

	return render(request, 'index.html', context)

def statistics(request):
	context = {'statistics_active': True}
	classes_context = []

	if is_teacher(request.user):
		classes = Class.objects.filter(teachers__in=[Teacher.objects.get(user=request.user)])
	else:
		classes = Class.objects.filter(students__in=[Student.objects.get(user=request.user)])

	for entry in classes:
		students = []
		for student in entry.students.all().order_by('user__first_name', 'user__last_name'):
			students.append({'name': str(student), 'total': student.total_value_in_class(entry)})
		classes_context.append((entry, students))

	context['classes'] = classes_context
	
	return render(request, 'reports.html', context)

rewards/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from jornada.util import is_teacher
from rewards.forms  import RewardForm, BadgeForm
from rewards.models import Reward, Badge
from accounts.models import Teacher, Student

# Create your views here.
@login_required(login_url='/usuario/login/')
def index(request):

	if not is_teacher(request.user):
		return redirect('index')
		# return render(request, 'students/student_rewards.html', {
		# 	'student': Student.objects.get(user=request.user),
		# 	'rewards': Student.objects.get(user=request.user).rewards.all(),
		# 	'badges': Student.objects.get(user=request.user).badges.all()
		# })

	return render(request, 'rewards/index.html', {
		'reward_form' : RewardForm(),
		'badge_form': BadgeForm(),
		'rewards' : Reward.objects.filter(created_by=request.user),
		'badges' : Badge.objects.filter(created_by=request.user),
		'rewards_active': True,
	})


@login_required(login_url='/usuario/login/')
def create_reward(request):

	if not is_teacher(request.user):
		return redirect('index')

	reward_form = RewardForm(request.POST or None)

	if reward_form.is_valid():
		reward = reward_form.save(commit=False)
		reward.created_by = request.user
		reward.save()
		# return redirect('index')

	return render(request, 'rewards/index.html', {
		'reward_form': reward_form,
		'badge_form' : BadgeForm(),
		'rewards' : Reward.object.filter(created_by=request.user),
		'badges' : Badge.object.filter(created_by=request.user),
	})


@login_required(login_url='/usuario/login/')
def create_badge(request):

	if not is_teacher(request.user):
		return redirect('index')

	badge_form = BadgeForm(request.POST or None)

	if badge_form.is_valid():
		badge = badge_form.save(commit=False)
		badge.created_by = request.user
		badge.save()
		#return redirect('index')

	print("COOOL")
	print(badge_form.errors)

	return render(request, 'rewards/index.html', {
		'badge_form': badge_form,
		'reward_form': RewardForm(),
		'rewards' : Reward.objects.filter(created_by=request.user),
		'badges' : Badge.objects.filter(created_by=request.user),
	})

jornada/templates/create_class.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

 <head>
    <meta charset="utf-8">
    <title>Cadastro de Turma - Jornada</title>

	   <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">

<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "css/bootstrap-responsive.min.css" %}" rel="stylesheet" type="text/css" />

<link href="{% static "css/font-awesome.css" %}" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet">

<link href="{% static "css/style.css" %}" rel="stylesheet" type="text/css">
<link href="{% static "css/pages/signin.css" %}" rel="stylesheet" type="text/css">

</head>

<body>

	<div class="navbar navbar-fixed-top">

	<div class="navbar-inner">

		<div class="container">

			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>

			<a class="brand" href="index.html">
				Jornada
			</a>

			<div class="nav-collapse">
				<ul class="nav pull-right">
					<li class="">
						<a href="login.html" class="">
							<i class="icon-chevron-left"></i> &nbsp;
							MUDAR ISSO DAQUI DEPOIS
						</a>

					</li>

				</ul>

			</div><!--/.nav-collapse -->

		</div> <!-- /container -->

	</div> <!-- /navbar-inner -->

</div> <!-- /navbar -->

<div class="container">
    <div class='row'>
        <div class='col-md-4'></div>
        <div class='col-md-4'>
          <script src='https://js.stripe.com/v2/' type='text/javascript'></script>
          <form accept-charset="UTF-8" action="/" class="require-validation" data-cc-on-file="false" data-stripe-publishable-key="pk_bQQaTxnaZlzv4FnnuZ28LFHccVSaj" id="payment-form" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓" /><input name="_method" type="hidden" value="PUT" /><input name="authenticity_token" type="hidden" value="qLZ9cScer7ZxqulsUWazw4x3cSEzv899SP/7ThPCOV8=" /></div>
            <div class='form-row'>
              <div class='col-xs-12 form-group required'>
                <label class='control-label'>Name on Card</label>
                <input class='form-control' size='4' type='text'>
              </div>
            </div>
            <div class='form-row'>
              <div class='col-xs-12 form-group card required'>
                <label class='control-label'>Card Number</label>
                <input autocomplete='off' class='form-control card-number' size='20' type='text'>
              </div>
            </div>
            <div class='form-row'>
              <div class='col-xs-4 form-group cvc required'>
                <label class='control-label'>CVC</label>
                <input autocomplete='off' class='form-control card-cvc' placeholder='ex. 311' size='4' type='text'>
              </div>
              <div class='col-xs-4 form-group expiration required'>
                <label class='control-label'>Expiration</label>
                <input class='form-control card-expiry-month' placeholder='MM' size='2' type='text'>
              </div>
              <div class='col-xs-4 form-group expiration required'>
                <label class='control-label'> </label>
                <input class='form-control card-expiry-year' placeholder='YYYY' size='4' type='text'>
              </div>
            </div>
            <div class='form-row'>
              <div class='col-md-12'>
                <div class='form-control total btn btn-info'>
                  Total:
                  <span class='amount'>$300</span>
                </div>
              </div>
            </div>
            <div class='form-row'>
              <div class='col-md-12 form-group'>
                <button class='form-control btn btn-primary submit-button' type='submit'>Pay »</button>
              </div>
            </div>
            <div class='form-row'>
              <div class='col-md-12 error form-group hide'>
                <div class='alert-danger alert'>
                  Please correct the errors and try again.
                </div>
              </div>
            </div>
          </form>
        </div>
        <div class='col-md-4'></div>
    </div>
</div>

<div class="class-container register">

	<div class="content clearfix">

		<form action="#" method="post">
			{% csrf_token %}
			<h1>Cadastro de Turma no Jornada</h1>

			<div class="create-class-fields">

				<p>Preencha os campos abaixo:</p>

				<div class="field">
					<label for="name">Nome</label>
					<input type="text" id="name" name="name" value="" placeholder="Nome da turma" class="classe" required/>
				</div> <!-- /field -->

        <div class="field">
					<p>Série:</p>
					<select class="classe" style=" font-size: 13px; color: #000; padding: 9px 15px 9px 4px; height:auto;  background-color: #fdfdfd; width: 100%; display: block; margin: 0; box-shadow: inset 2px 2px 4px #f1f1f1;" name="grade">
						{% for value, grade in grades %}
						<option value="{{ value }}">{{ grade }}</option>
						{% endfor %}					</select>
				</div> <!-- /field -->

				<div class="field">
					<label for="discipline">Disciplina</label>
					<input type="text" id="discipline" name="discipline" value="" placeholder="Disciplina" class="classe"/>
				</div> <!-- /field -->

				<div class="field">
					<label for="time">Horário</label>
					<input type="text" id="time" name="time" value="" placeholder="Horário" class="classe  "/>
				</div> <!-- /field -->

				<div class="field">
					<label for="location">Local</label>
					<input type="text" id="location" name="location" value="" placeholder="Local" class="classe"/>
				</div> <!-- /field -->

        <p><strong>Dados adicionais</strong></p>

        <div class="field">
					<label for="description">Descrição</label>
					<input type="text" id="description" name="description" value="" placeholder="Descrição" class="classe"/>
				</div> <!-- /field -->

			</div> <!-- /login-fields -->

			<div class="create-class-actions">

				<!--<span class="login-checkbox">
					<input id="Field" name="Field" type="checkbox" class="field login-checkbox" value="First Choice" tabindex="4" />
					<label class="choice" for="Field">Agree with the Terms & Conditions.</label>
				</span>-->

				<button class="button btn btn-primary btn-large">Criar Turma</button>

			</div> <!-- .actions -->

		</form>

	</div> <!-- /content -->

</div> <!-- /account-container -->


<!-- Text Under Box -->
<div class="create-class-extra">
	Mudar isso daqui tbm, ne?<a href="login.html"> E isso tbm</a>
</div> <!-- /login-extra -->


<script src="{% static "js/jquery-1.7.2.min.js" %}"></script>
<script src="{% static "js/bootstrap.js" %}"></script>

<script src="{% static "js/signin.js" %}"></script>

</body>

 </html>

jornada/templates/footer.html
<div class="footer">
  <div class="footer-inner">
    <div class="container">
      <div class="row">
        <div class="span12"> &copy; 2015 <a href="http://www.egrappler.com/">Jornada</a>. </div>
        <!-- /span12 --> 
      </div>
      <!-- /row --> 
    </div>
    <!-- /container --> 
  </div>
  <!-- /footer-inner --> 
</div>

jornada/templates/nav.html
<div class="navbar-wrapper">
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Bem vindo ao <strong>Jornada</strong></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="icon-user"></i> &nbsp; {{ request.user.first_name }} {{ request.user.last_name }} <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'Accounts:edit' %}">Configurações</a></li>
          <li class="divider"></li>
          <li><a href="{% url 'Accounts:logout' %}">Sair</a></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div>
</nav>
</div>

<div class="subnavbar">
  <div class="subnavbar-inner">
    <div class="container">
      <ul class="mainnav">
        <li {% if index_active %}class="active"{% endif%}><a href="{% url 'index' %}"><i class="icon-home"></i><span>Home</span> </a> </li>
        <li {% if classes_active %}class="active"{% endif%}><a href="{% url 'Classes:index' %}"><i class="icon-list-alt"></i><span>Turmas</span> </a> </li>
        <li {% if rewards_active %}class="active"{% endif%}><a href="{% url 'Rewards:index' %}"><i class="icon-ok-sign"></i><i class="icon-trophy"></i><span>Pontuações e Badges</span> </a> </li>
      </ul>
    </div>
    <!-- /container --> 
  </div>
  <!-- /subnavbar-inner --> 
</div>

jornada/templates/signup_student.html
{% load staticfiles %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">

 <head>
    <meta charset="utf-8">
    <title>Cadastro - Jornada</title>

	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">

<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "css/bootstrap-responsive.min.css" %}" rel="stylesheet" type="text/css" />

<link href="{% static "css/font-awesome.css" %}" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet">

<link href="{% static "css/style.css" %}" rel="stylesheet" type="text/css">
<link href="{% static "css/pages/signin.css" %}" rel="stylesheet" type="text/css">

<style type="text/css">
	
	select{
		font-family: 'Open Sans';
	    font-size: 13px;
	    color: #8e8d8d;
	    padding: 9px 15px 9px 0px;
	    background-color: #fdfdfd;
	    width: 100%;
	    display: block;
	    margin: 0;
	    height: auto;
	    box-shadow: inset 2px 2px 4px #f1f1f1;
	}

</style>

</head>

<body>

	<div class="navbar navbar-fixed-top">

	<div class="navbar-inner">

		<div class="container">

			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>

			<a class="brand" href="{% url 'index' %}">
				Jornada
			</a>

			<div class="nav-collapse">
				<ul class="nav pull-right">
					<li class="">
						<a href="{% url 'Accounts:login' %}" class="">
							<i class="icon-chevron-left"></i> &nbsp;
							Já possui uma conta? Faça o login
						</a>

					</li>

				</ul>

			</div><!--/.nav-collapse -->

		</div> <!-- /container -->

	</div> <!-- /navbar-inner -->

</div> <!-- /navbar -->


<div class="account-container register">

	<div class="content clearfix">

		<form action="#" method="post">
			{% csrf_token %}
			<h1>Cadastro de aluno no Jornada</h1>

			<div class="login-fields">

				<p>Preencha os campos abaixo:</p>

				<div class="field">
					<label for="firstname">Nome</label>
					{% render_field form.first_name placeholder=form.first_name.label %}
					<div class="form-error">{{ form.first_name.errors }}</div>
				</div> <!-- /field -->

				<div class="field">
					<label for="lastname">Sobrenome:</label>
					{% render_field form.last_name placeholder=form.last_name.label %}
					<div class="form-error">{{ form.last_name.errors }}</div>
				</div> <!-- /field -->


				<div class="field">
					<label for="email">Email:</label>
					{% render_field form.email placeholder=form.email.label %}
					<div class="form-error">{{ form.email.errors }}</div>
				</div> <!-- /field -->

				<div class="field">
					<label for="username">Nome de usuário:</label>
					{% render_field form.username placeholder=form.username.label %}
					<div class="form-error">{{ form.username.errors }}</div>
				</div> <!-- /field -->

				<div class="field">
					<label for="password">Senha:</label>
					{% render_field form.password placeholder=form.password.label type="password" %}
					<div class="form-error">{{ form.password.errors }}</div>
				</div> <!-- /field -->

				<p><strong>Dados adicionais</strong></p>

				<div class="field">
					<p>Série:</p>
					{% render_field student_form.grade placeholder=student_form.grade.label %}
				</div> <!-- /field -->

				<div class="field">
					<label for="school">Escola:</label>
					{% render_field student_form.school placeholder='Escola em que estuda' %}
				</div> <!-- /field -->


			</div> <!-- /login-fields -->

			<div class="login-actions">

				<!--<span class="login-checkbox">
					<input id="Field" name="Field" type="checkbox" class="field login-checkbox" value="First Choice" tabindex="4" />
					<label class="choice" for="Field">Agree with the Terms & Conditions.</label>
				</span>-->

				<button class="button btn btn-primary btn-large">Registrar</button>

			</div> <!-- .actions -->

		</form>

	</div> <!-- /content -->

</div> <!-- /account-container -->


<!-- Text Under Box -->
<div class="login-extra">
	Já possui uma conta?<a href="{% url 'Accounts:login'%}"> Clique aqui para fazer o login</a>
</div> <!-- /login-extra -->


<script src="{% static "js/jquery-1.7.2.min.js" %}"></script>
<script src="{% static "js/bootstrap.js" %}"></script>

<script src="{% static "js/signin.js" %}"></script>

</body>

 </html>

jornada/templates/signup_teacher.html
{% load staticfiles %}
{% load widget_tweaks %}


<!DOCTYPE html>
<html lang="en">
  
 <head>
    <meta charset="utf-8">
    <title>Cadastro - Jornada</title>

	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes"> 
    
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "css/bootstrap-responsive.min.css" %}" rel="stylesheet" type="text/css" />

<link href="{% static "css/font-awesome.css" %}" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet">
    
<link href="{% static "css/style.css" %}" rel="stylesheet" type="text/css">
<link href="{% static "css/pages/signin.css" %}" rel="stylesheet" type="text/css">

</head>

<body>
	
	<div class="navbar navbar-fixed-top">
	
	<div class="navbar-inner">
		
		<div class="container">
			
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			
			<a class="brand" href="index.html">
				Jornada			
			</a>		
			
			<div class="nav-collapse">
				<ul class="nav pull-right">
					<li class="">						
						<a href="{% url 'Accounts:login'%}" class="">
							<i class="icon-chevron-left"></i> &nbsp;
							Já possui uma conta? Faça o login
						</a>
						
					</li>

				</ul>
				
			</div><!--/.nav-collapse -->	
	
		</div> <!-- /container -->
		
	</div> <!-- /navbar-inner -->
	
</div> <!-- /navbar -->

<div class="account-container register">
	
	<div class="content clearfix">
		
		<form action="#" method="post">
			{% csrf_token %}
			<h1>Cadastro de professor no Jornada</h1>			
			
			<div class="login-fields">
				
				<p>Preencha os campos abaixo:</p>
				
				<div class="field">
					<label for="firstname">Nome</label>

					{% render_field form.first_name placeholder=form.first_name.label %}
					<div class="form-error">{{ form.first_name.errors }}</div>
				</div> <!-- /field --> 
				
				<div class="field">
					<label for="lastname">Sobrenome:</label>	
					
					{% render_field form.last_name placeholder=form.last_name.label %}

					<div class="form-error">{{ form.last_name.errors }}</div>
				</div> <!-- /field -->
				
				
				<div class="field">
					<label for="email">Email:</label>

					{% render_field form.email placeholder=form.email.label %}
					<div class="form-error">{{ form.email.errors }}</div>
				</div> <!-- /field -->
				
				<div class="field">
					<label for="username">Nome de usuário:</label>

					{% render_field form.username placeholder=form.username.label %}
					<div class="form-error">{{ form.username.errors }}</div>
				</div> <!-- /field -->

				<div class="field">
					<label for="password">Senha:</label>

					{% render_field form.password placeholder=form.password.label type="password" %}
					<div class="form-error">{{ form.password.errors }}</div>
				</div> <!-- /field -->



				<p><strong>Dados adicionais</strong></p>

				<div class="field">
					<label for="email">Escola:</label>					
					{% render_field teacher_form.school placeholder='Escola em que leciona' %}
				</div> <!-- /field -->

				<div class="field">
					<label for="email">Disciplinas:</label>
					{% render_field teacher_form.disciplines placeholder=teacher_form.disciplines.label %}
				</div> <!-- /field -->


			</div> <!-- /login-fields -->
			
			<div class="login-actions">
				
				<!--<span class="login-checkbox">
					<input id="Field" name="Field" type="checkbox" class="field login-checkbox" value="First Choice" tabindex="4" />
					<label class="choice" for="Field">Agree with the Terms & Conditions.</label>
				</span>-->
									
				<button class="button btn btn-primary btn-large">Registrar</button>
				
			</div> <!-- .actions -->
			
		</form>
		
	</div> <!-- /content -->
	
</div> <!-- /account-container -->


<!-- Text Under Box -->
<div class="login-extra">
	Já possui uma conta?<a href="{% url 'Accounts:login'%}"> Clique aqui para fazer o login</a>
</div> <!-- /login-extra -->


<script src="{% static "js/jquery-1.7.2.min.js" %}"></script>
<script src="{% static "js/bootstrap.js" %}"></script>

<script src="{% static "js/signin.js" %}"></script>

</body>

 </html>